{% set version = "1.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gglasso
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gglasso_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gglasso/gglasso_{{ version }}.tar.gz
  sha256: 2ee61c85b3ab5aa6f6bb4c32aaec972907f3948f64148626ae53917339745abd

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('gglasso')"           # [not win]
    - "\"%R%\" -e \"library('gglasso')\""  # [win]

about:
  home: https://github.com/emeryyi/gglasso
  license: GPL-2.0-only
  summary: 'A unified algorithm, blockwise-majorization-descent (BMD), for efficiently computing the solution paths of the group-lasso penalized least squares, logistic regression, Huberized SVM and squared SVM. The package is an implementation of Yang, Y. and Zou, H. (2015) DOI: <doi:10.1007/s11222-014-9498-5>.'
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gglasso
# Title: Group Lasso Penalized Learning Using a Unified BMD Algorithm
# Version: 1.5
# Date: 2020-3-01
# Authors@R: c( person("Yi", "Yang", email = "yi.yang6@mcgill.ca", role = c("aut", "cre"), comment = "http://www.math.mcgill.ca/yyang/"), person("Hui", "Zou", email = "hzou@stat.umn.edu", role = c("aut"), comment = "http://users.stat.umn.edu/~zouxx019/"), person("Sahir", "Bhatnagar", email = "sahir.bhatnagar@gmail.com", role = c("aut"), comment = "http://sahirbhatnagar.com/") )
# Maintainer: Yi Yang <yi.yang6@mcgill.ca>
# Description: A unified algorithm, blockwise-majorization-descent (BMD), for efficiently computing the solution paths of the group-lasso penalized least squares, logistic regression, Huberized SVM and squared SVM. The package is an implementation of Yang, Y. and Zou, H. (2015) DOI: <doi:10.1007/s11222-014-9498-5>.
# License: GPL-2
# Imports: methods
# URL: https://github.com/emeryyi/gglasso
# BugReports: https://github.com/emeryyi/gglasso/issues
# Packaged: 2020-03-18 05:48:51 UTC; yiyang
# Repository: CRAN
# Date/Publication: 2020-03-18 07:00:08 UTC
# RoxygenNote: 7.0.2
# Suggests: testthat, knitr, rmarkdown
# Encoding: UTF-8
# LazyData: TRUE
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Author: Yi Yang [aut, cre] (http://www.math.mcgill.ca/yyang/), Hui Zou [aut] (http://users.stat.umn.edu/~zouxx019/), Sahir Bhatnagar [aut] (http://sahirbhatnagar.com/)
